server:
  port: 8081
spring:
  application:
    name: eureka-client
eureka:
  client:
#    service-url:
#      defaultZone: http://wjj:wzzst310@localhost:8761/eureka/
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://wjj:wzzst310@172.16.110.23:8761/eureka/
