

#升级脚本位置，可以多个，可以给每个环境使用不同位置
##如果我们并不是在项目初就加flyway的话，则在有历史数据的情况下，加入flyway后，将会出现：set baselineOnMigrate to true to initialize the schema history table.解决方法将baselineOnMigrate设置为true。注意，不同版本的设置方法并不相同。有的版本是：spring.flyway.baselineOnMigrate有的则是flyway.baselineOnMigrate
spring:
  flyway:
    clean-disabled: true #禁止flyway执行清理
    ignore-missing-migrations: true #忽略缺失的升级脚本验证
    locations: classpath:db/migration,classpath:test/db/migration
    baseline-on-migrate: true