server:
  port: 10002
spring:
  application:
    name: zuul-eureka-multizone
eureka:
  instance:
    metadata-map.zone: zone3
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-west
    service-url:
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    availability-zones:
      region-west: zone3,zone4

