spring:
  rabbitmq:
    addresses: 129.204.35.106:5672
    username: wjj
    password: wzzst310
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true