server:
  port: 8012
spring:
  application:
    name: consumer-ribbon-loadbalance
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

provider-ribbon-loadbalance:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
provider-ribbon-loadbalance-b:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule